server:
   address: localhost

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HMS
    username: root
    password: Apple123$$
  application:
      name: USERS
eureka:
   instance: 
        hostname: localhost
        appname: users
        #instance-id: spring.application.name:$random-value
        status-page-url-path: /welcome
   client:
      eureka-server-port: 8085
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
         defaultZone: http://ec2-13-235-76-64.ap-south-1.compute.amazonaws.com:8761/eureka, http://order-service:8084/eureka, http://search-service:8086/eureka
      
