server:
   address: localhost

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:hmsinstance2.cocqydkvpsq8.ap-south-1.rds.amazonaws.com}:3306/hms
    username: root
    password: Apple123$$
