server:
      port: 8086
      address: localhost
      servlet:
        context-path: /search-context
        
        

eureka:
   instance: 
        hostname: localhost
        appname: search
        status-page-url-path: /swagger-ui.html
        #instance-id: spring.application.name:$random-value
   client:
      eureka-server-port: 8084
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
         defaultZone: http://ec2-13-235-76-64.ap-south-1.compute.amazonaws.com:8761/eureka, http://user-service:8085/eureka, http://order-service:8084/eureka
              
#
#eureka: 
#  instance: 
#     hostname: search-service
#     appname: search
#     status-page-url-path: /swagger-ui.html
#     #preferIpAddress: true
#  client:
#      eureka-server-port: 8086
#      register-with-eureka: true
#      fetch-registry: true
#      serviceUrl:  
#        default-zone: http://ec2-13-235-76-64.ap-south-1.compute.amazonaws.com:8761/eureka, http://order-service:8084/eureka, http://user-service:8085/eureka
#                    
      
 
# eureka:
#    instance: 
#    hostname: user-service
#    appname: usr 
#    instance-id: spring.application.name:$random-value
#  client:
#    eureka-server-port: 8085
#    register-with-eureka: false
#    fetch-registry: true
#    serviceUrl:  
#        default-zone: http://eureka-primary:8086/eureka,http://order-service:8084/eureka, http://user-service:8085/eureka
#      

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:hmsinstance2.cocqydkvpsq8.ap-south-1.rds.amazonaws.com}:3306/hms
    username: root
    password: Apple123$$
  application:
      name: searchmanagement
#  cloud:
#    config:
#      uri: http://localhost:8889      
      
logging:
    level:
      web: trace


log4j2.contextSelector: org.apache.logging.log4j.core.async.AsyncLoggerContextSelector   

##Zuul
#zuul:
#  routes:
#    order-service:
#      url: 
#        http://localhost:8084/eureka
#    user-service:
#      url: 
#        http://localhost:8085/eureka      
    
    
   
  
#security:
#        oauth2:
#              client:
#                    clientId : 867032803412-qcgl21dqcmiin5r8ck5akdfkqbmqd5fd.apps.googleusercontent.com
#                    clientSecret : uxeu9IKwkvA8lqfnbtMTbrsD
#                    accessTokenUri  :  https://www.googleapis.com/oauth2/v3/token
#                    userAuthorizationUri  :  https://accounts.google.com/o/oauth2/auth
#                    tokenName : oauth_token
#                    authenticationScheme : query
#                    clientAuthenticationScheme : form
#                    scope : profile email
#              resource:
#                      userInfoUri  :  https://www.googleapis.com/userinfo/v2/me
#                      preferTokenInfo : false      
#      
      
    
  
  
       
      
